[build]
  publish = "."  

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless", "nodemailer", "dotenv"]
  included_files = ["./netlify/functions/.env"]